// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Pvpdata
{

using global::System;
using global::FlatBuffers;

public struct Mapeffect : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Mapeffect GetRootAsMapeffect(ByteBuffer _bb) { return GetRootAsMapeffect(_bb, new Mapeffect()); }
  public static Mapeffect GetRootAsMapeffect(ByteBuffer _bb, Mapeffect obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Mapeffect __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Effectnum1 { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Effectnum2 { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Effectnum3 { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Effectnum4 { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Effectnum5 { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<Mapeffect> CreateMapeffect(FlatBufferBuilder builder,
      int effectnum1 = 0,
      int effectnum2 = 0,
      int effectnum3 = 0,
      int effectnum4 = 0,
      int effectnum5 = 0) {
    builder.StartObject(5);
    Mapeffect.AddEffectnum5(builder, effectnum5);
    Mapeffect.AddEffectnum4(builder, effectnum4);
    Mapeffect.AddEffectnum3(builder, effectnum3);
    Mapeffect.AddEffectnum2(builder, effectnum2);
    Mapeffect.AddEffectnum1(builder, effectnum1);
    return Mapeffect.EndMapeffect(builder);
  }

  public static void StartMapeffect(FlatBufferBuilder builder) { builder.StartObject(5); }
  public static void AddEffectnum1(FlatBufferBuilder builder, int effectnum1) { builder.AddInt(0, effectnum1, 0); }
  public static void AddEffectnum2(FlatBufferBuilder builder, int effectnum2) { builder.AddInt(1, effectnum2, 0); }
  public static void AddEffectnum3(FlatBufferBuilder builder, int effectnum3) { builder.AddInt(2, effectnum3, 0); }
  public static void AddEffectnum4(FlatBufferBuilder builder, int effectnum4) { builder.AddInt(3, effectnum4, 0); }
  public static void AddEffectnum5(FlatBufferBuilder builder, int effectnum5) { builder.AddInt(4, effectnum5, 0); }
  public static Offset<Mapeffect> EndMapeffect(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Mapeffect>(o);
  }
};


}
